# Generated by Django 4.1.7 on 2023-03-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='firstname',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='lastname',
            new_name='title',
        ),
    ]
